language: php
dist: xenial

php:
  - 7.3

services:
  - mysql

addons:
  chrome: stable

install:
  - cp .env.travis .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - mysql -e 'create database homestead;'
  - php artisan key:generate

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs --standard=PSR1,PSR2 --colors --runtime-set ignore_warnings_on_exit 1 app
  - php artisan dusk